# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Cache-Memcached
version:      0.02
version_from: lib/Sledge/Cache/Memcached.pm
installdirs:  site
requires:
    Cache::Memcached:              1.15
    Sledge::Cache:                 0.01
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
